iruka/Iruka/Controllers/CouponsController.cs
using AutoMapper;
using Iruka.EF.Model;
using Iruka.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace Iruka.Controllers
{
    public class CouponsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Coupons
        public ActionResult Index()
        {
            ViewBag.UserId = User.Identity.GetUserId(); return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(CouponDto couponDto)
        {
            if (ModelState.IsValid)
            {
                var userId = User.Identity.GetUserId();
                var coupon = Mapper.Map<CouponDto, Coupon>(couponDto);
                coupon.NewCreatedData(userId);
                db.Coupons.Add(coupon);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserId = User.Identity.GetUserId(); return View(couponDto);
        }

        // GET: Coupons/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Coupon coupon = db.Coupons.Find(id);
            if (coupon == null)
            {
                return HttpNotFound();
            }

            var couponDto = Mapper.Map<Coupon, CouponDto>(coupon);

            ViewBag.UserId = User.Identity.GetUserId(); return View(couponDto);
        }

        // POST: Coupons/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CouponDto couponDto)
        {
            if (ModelState.IsValid)
            {
                var userId = User.Identity.GetUserId();
                var coupon = db.Coupons.SingleOrDefault(x => x.Id == couponDto.Id);
                coupon = Mapper.Map(couponDto, coupon);
                coupon.SetModifiedData(userId);
                db.Entry(coupon).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserId = User.Identity.GetUserId(); return View(couponDto);
        }

        [HttpPost]
        public ActionResult Delete(Guid id)
        {
            try
            {
                Coupon coupon = db.Coupons.Find(id);
                coupon.SetIsActive(false, User.Identity.GetUserId());
                db.SaveChanges();
                return Json(new { success = "Success" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                return Json(new { error = "Error" }, JsonRequestBehavior.AllowGet);
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

iruka/Iruka/Views/Coupons/Edit.cshtml
@model Iruka.Models.CouponDto

@section js {
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/js/cleave.min.js"></script>
    <script src="~/Scripts/js/coupon.js"></script>
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.Id)

    <div class="row">
        <div class="col-lg-6 col-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h2>
                        Edit Coupon
                        <a href="/Coupons/Index/"><i class="fa fa-arrow-circle-left float-right" aria-hidden="true"></i></a>
                    </h2>
                    <hr />

                    <div class="form-group row">
                        @Html.LabelFor(m => m.CouponType, new { @class = "col-12 control-label" })
                        <div class="col-12">
                            @Html.EnumDropDownListFor(m => m.CouponType, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.CouponType, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group row">
                        @Html.LabelFor(m => m.PointPrice, new { @class = "col-12 control-label" })
                        <div class="col-12">
                            @Html.TextBoxFor(m => m.PointPrice, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.PointPrice, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group row">
                        @Html.LabelFor(m => m.Amount, new { @class = "col-12 control-label" })
                        <div class="col-12">
                            @Html.TextBoxFor(m => m.Amount, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Amount, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div id="discount-section" class="form-group row d-none">
                        @Html.LabelFor(model => model.DiscountValue, htmlAttributes: new { @class = "control-label col-12" })
                        <div class="col-12" style="display: flex; align-content: center">
                            @Html.EnumDropDownListFor(model => model.DiscountType, htmlAttributes: new { @class = "form-control", @style = "width: 80px; background-color: #5aa0b3; color: white" })
                            @Html.EditorFor(model => model.DiscountValue, new { htmlAttributes = new { @class = "form-control numeral" } })
                        </div>
                        @Html.ValidationMessageFor(m => m.DiscountValue, "", new { @class = "text-danger" })
                    </div>

                    <div id="product-section" class="form-group row d-none">
                        @Html.LabelFor(m => m.FreeProduct, new { @class = "col-12 control-label" })
                        <div class="col-12">
                            @Html.TextBoxFor(m => m.FreeProduct, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.FreeProduct, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <button type="button" onclick="confirmSubmit(this.form)" class="btn btn-success btn-fw float-right">
                        <i class="fa fa-floppy-o" aria-hidden="true"></i> Save Changes
                    </button>
                </div>
            </div>
        </div>
    </div>
}

iruka/Iruka/Views/Coupons/Index.cshtml
@using Iruka.DAL
@model Iruka.Models.CouponDto

@{
    ViewBag.Title = "Index";
}

@section js {
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/js/cleave.min.js"></script>
    <script src="~/Scripts/js/coupon.js"></script>
    <script>
        $(function () {
            InitActiveCouponsDataTable();
        });

        function InitActiveCouponsDataTable() {
            couponDataTable = $('#active-coupons-table').DataTable({
                responsive: true,
                "pageLength": 10,
                "order": [],
                "bLengthChange": false,
                "bInfo": false
            });
        }
    </script>
}

@using (Html.BeginForm())
{

    @Html.AntiForgeryToken()

    <div class="row">
        <div class="col-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h2>Create New Coupon</h2>
                    <hr />
                    <div class="row">
                        <div class="col-lg-6 col-12">
                            <fieldset>
                                <div class="form-group row">
                                    @Html.LabelFor(m => m.CouponType, new { @class = "col-12 control-label" })
                                    <div class="col-12">
                                        @Html.EnumDropDownListFor(m => m.CouponType, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(m => m.CouponType, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group row">
                                    @Html.LabelFor(m => m.PointPrice, new { @class = "col-12 control-label" })
                                    <div class="col-12">
                                        @Html.TextBoxFor(m => m.PointPrice, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(m => m.PointPrice, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group row">
                                    @Html.LabelFor(m => m.Amount, new { @class = "col-12 control-label" })
                                    <div class="col-12">
                                        @Html.TextBoxFor(m => m.Amount, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(m => m.Amount, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div id="discount-section" class="form-group row d-none">
                                    @Html.LabelFor(model => model.DiscountValue, htmlAttributes: new { @class = "control-label col-12" })
                                    <div class="col-12" style="display: flex; align-content: center">
                                        @Html.EnumDropDownListFor(model => model.DiscountType, htmlAttributes: new { @class = "form-control", @style = "width: 80px; background-color: #5aa0b3; color: white" })
                                        @Html.EditorFor(model => model.DiscountValue, new { htmlAttributes = new { @class = "form-control numeral" } })
                                    </div>
                                    @Html.ValidationMessageFor(m => m.DiscountValue, "", new { @class = "text-danger" })
                                </div>

                                <div id="product-section" class="form-group row d-none">
                                    @Html.LabelFor(m => m.FreeProduct, new { @class = "col-12 control-label" })
                                    <div class="col-12">
                                        @Html.TextBoxFor(m => m.FreeProduct, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(m => m.FreeProduct, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <button type="button" onclick="confirmSubmit(this.form)" class="btn btn-success btn-fw float-right">
                                    <i class="fa fa-plus-circle" aria-hidden="true"></i><span class="font-weight-bold">Create</span>
                                </button>
                            </fieldset>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h3>Coupon List</h3>
                    <hr />
                    <table class="table table-hover table-bordered" style="width: 100% !important" id="active-coupons-table">
                        <thead>
                            <tr>
                                <th> Coupon Type </th>
                                <th> Value </th>
                                <th> Price in Point </th>
                                <th> Amount </th>
                                <th> Purchased </th>
                                <th> Action </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in CouponDal.GetAllActiveCoupons())
                            {
                                <tr>
                                    <td>@item.CouponTypeValue</td>
                                    <td>@item.CouponValue</td>
                                    <td>@item.PointPrice.ToString("N0")</td>
                                    <td>@item.Amount</td>
                                    <td>@item.Purchased</td>
                                    <td style="width:10%">
                                        @*<button type="button" class="btn btn-secondary btn-fw" onclick="location.href='@Url.Action("Edit", "Coupons", new {id = item.Id })'" style="min-width:50px">
                                                <i class="mdi mdi-pencil" style="margin:0px"></i>
                                            </button>*@
                                        <button type="button" class="btn btn-danger btn-fw" onclick="deleteCoupon('@item.Id')" style="min-width:50px">
                                            <i class="mdi mdi-delete" style="margin:0px" aria-hidden="true"></i>
                                        </button>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
}